USE `Spain` ;
insert into Spain.Provincias values(1,"Araba/Álava",16);
insert into Spain.Provincias values(2,"Albacete",7);
insert into Spain.Provincias values(3,"Alicante/Alacant",17);
insert into Spain.Provincias values(4,"Almería",1);
insert into Spain.Provincias values(5,"Ávila",8);
insert into Spain.Provincias values(6,"Badajoz",10);
insert into Spain.Provincias values(7,"Balears, Illes",4);
insert into Spain.Provincias values(8,"Barcelona",9);
insert into Spain.Provincias values(9,"Burgos",8);
insert into Spain.Provincias values(10,"Cáceres",10);
insert into Spain.Provincias values(11,"Cádiz",1);
insert into Spain.Provincias values(12,"Castellón/Castelló",17);
insert into Spain.Provincias values(13,"Ciudad Real",7);
insert into Spain.Provincias values(14,"Córdoba",1);
insert into Spain.Provincias values(15,"Coruña, A",11);
insert into Spain.Provincias values(16,"Cuenca",7);
insert into Spain.Provincias values(17,"Girona",9);
insert into Spain.Provincias values(18,"Granada",1);
insert into Spain.Provincias values(19,"Guadalajara",7);
insert into Spain.Provincias values(20,"Gipuzkoa",16);
insert into Spain.Provincias values(21,"Huelva",1);
insert into Spain.Provincias values(22,"Huesca",2);
insert into Spain.Provincias values(23,"Jaén",1);
insert into Spain.Provincias values(24,"León",8);
insert into Spain.Provincias values(25,"Lleida",9);
insert into Spain.Provincias values(26,"Rioja, La",12);
insert into Spain.Provincias values(27,"Lugo",11);
insert into Spain.Provincias values(28,"Madrid",13);
insert into Spain.Provincias values(29,"Málaga",1);
insert into Spain.Provincias values(30,"Murcia",14);
insert into Spain.Provincias values(31,"Navarra",15);
insert into Spain.Provincias values(32,"Ourense",11);
insert into Spain.Provincias values(33,"Asturias",3);
insert into Spain.Provincias values(34,"Palencia",8);
insert into Spain.Provincias values(35,"Palmas, Las",5);
insert into Spain.Provincias values(36,"Pontevedra",11);
insert into Spain.Provincias values(37,"Salamanca",8);
insert into Spain.Provincias values(38,"Santa Cruz de Tenerife",5);
insert into Spain.Provincias values(39,"Cantabria",6);
insert into Spain.Provincias values(40,"Segovia",8);
insert into Spain.Provincias values(41,"Sevilla",1);
insert into Spain.Provincias values(42,"Soria",8);
insert into Spain.Provincias values(43,"Tarragona",9);
insert into Spain.Provincias values(44,"Teruel",2);
insert into Spain.Provincias values(45,"Toledo",7);
insert into Spain.Provincias values(46,"Valencia/València",17);
insert into Spain.Provincias values(47,"Valladolid",8);
insert into Spain.Provincias values(48,"Bizkaia",16);
insert into Spain.Provincias values(49,"Zamora",8);
insert into Spain.Provincias values(50,"Zaragoza",2);
insert into Spain.Provincias values(51,"Ceuta",18);
insert into Spain.Provincias values(52,"Melilla",19);
