USE `Spain` ;
insert into Spain.Regiones values(1,"Andalucía");
insert into Spain.Regiones values(2,Aragón);
insert into Spain.Regiones values(3,Principado de Asturias);
insert into Spain.Regiones values(4,Baleares);
insert into Spain.Regiones values(5,Canarias);
insert into Spain.Regiones values(6,Cantabria);
insert into Spain.Regiones values(7,Castilla-La Mancha);
insert into Spain.Regiones values(8,Castilla y León);
insert into Spain.Regiones values(9,Cataluña);
insert into Spain.Regiones values(10,Extremadura);
insert into Spain.Regiones values(11,Galicia);
insert into Spain.Regiones values(12,La Rioja);
insert into Spain.Regiones values(13,Comunidad de Madrid);
insert into Spain.Regiones values(14,Región de Murcia);
insert into Spain.Regiones values(15,Comunidad Foral de Navarra);
insert into Spain.Regiones values(16,País Vasco);
insert into Spain.Regiones values(17,Comunidad Valenciana);
insert into Spain.Regiones values(18,Ceuta);
insert into Spain.Regiones values(19,Melilla);
